# Generated by Django 3.0.6 on 2020-07-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
