# Generated by Django 3.0.6 on 2020-07-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20200723_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
