# Generated by Django 3.0.6 on 2020-07-24 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20200723_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
