# Generated by Django 3.0.6 on 2020-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_of_registration',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
