# Generated by Django 3.0.6 on 2020-07-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_end_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
