# Generated by Django 3.0.5 on 2020-04-22 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('forehand', models.CharField(choices=[('LEFT', 'Leworęczny'), ('RIGHT', 'Praworęczny'), ('-', '-')], default='-', max_length=10)),
                ('backhand', models.CharField(choices=[('ONE', 'Jednoręczny'), ('TWO', 'Dwuręczny'), ('-', '-')], default='-', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
