# Generated by Django 3.0.5 on 2020-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200422_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisprofile',
            name='backhand',
            field=models.CharField(blank=True, choices=[('ONE', 'Jednoręczny'), ('TWO', 'Dwuręczny'), ('-', '-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tennisprofile',
            name='forehand',
            field=models.CharField(blank=True, choices=[('LEFT', 'Leworęczny'), ('RIGHT', 'Praworęczny'), ('-', '-')], max_length=10, null=True),
        ),
    ]
